### ISSUE TITLE
Check for return date > depart date.

### ISSUE THREAD

**Issue by sophiebuckley** [NBuckley2013/flight-search#1]
Hey Neil,

Just thought I'd have a bit of a look at the changes you've made to your 'Flight Search' project. One thing I noticed while I was using it is that there isn't a check for whether the depart date is before the return date. I selected the depart date as 12/02/2019 and the return date as 22/09/2018. Whilst it did show that there were obviously no flights, I was just thinking that maybe there should be an error message of some sort, or a flag incase the user has made a mistake?

<img width="1440" alt="screen shot 2018-09-22 at 12 13 25" src="https://user-images.githubusercontent.com/6482606/45916656-8064e080-be61-11e8-8334-e4c26169edd4.png">

<img width="1440" alt="screen shot 2018-09-22 at 12 13 31" src="https://user-images.githubusercontent.com/6482606/45916655-8064e080-be61-11e8-9d91-330fec468144.png">

Apart from that, it's looking great! I'm glad the auto-fill suggestions for the airports now works. :)

Sophie x

**Comment by NBuckley2013** [comment]
Thanks Sophie, I've added a check to ensure the return date is greater than the depature date.

https://github.com/NBuckley2013/flight-search/commit/dab05d84140c041e506ef46b79b149839e584918
